name: Go package

on: [push]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
          cache: false
      - uses: actions/checkout@v3

      - name: Vendor
        run: go mod vendor

      - name: Lint 
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'

      - name: Generate 
        run: |
          go generate -v ./...
          git diff --exit-code || (echo "Please generate assembly by running 'go generate ./...'" && false)

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
